### PR TITLE
add initail devpack.com definition

### PR DESCRIPTION
**Pull request by zzonsang**
Devpack platform updates.

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Hi, I cannot see any offering at that URL?!

**Comment by zzonsang** [comment]
Hi, I fixed the devpack site url(https://devpack.co.kr).
quick information url : https://www.cloudpack.co.kr/portal/ktcloudportal.epc.productintro.ucloud_server_image.devpack.html

Thank you.

**Comment by stefan-kolb** [comment]
We still need two logos, see https://github.com/stefan-kolb/paas-profiles/blob/master/CONTRIBUTING.md#how-to-add-a-new-profile
Also please change the country in infrastructures to the ISO country code for Korea `KR`. Otherwise the profile looks good!

**Comment by stefan-kolb** [comment]
@zzonsang Can you please add the two missing logos? I can merge your request afterwards! :smile:

**Comment by zzonsang** [comment]
You can not upload the file to the company policy.
So I've uploaded from the outside.

Thank you.

**Comment by stefan-kolb** [comment]
What do you mean by that?

Am 01.08.2016 2:53 nachm. schrieb "Cho hyun sang" <notifications@github.com

**Pull request merged**
