### PR TITLE
Podspace

### PR DESCRIPTION
**Pull request by podspace**
Hello. Please add PodSpace. Thank you :)

### CODE REVIEW

**Comment by mbalazs** [comment]
Yes, that would be great! Is this something that should be specified in the JSON file? We have looked at the other JSONs but we didn't see an attribute for that.

**Comment by JohannesRudolph** [comment]
iirc theres also a platforms.json file in the repo that has the mappings
from platforms to paas providers. Its a pity this hasnt been changed yet so
that the mapping could be specified in the same json file. I think there
were some plans for such a change but its up for grabs for someone to do
something about it.


mbalazs <notifications@github.com> schrieb am Do., 9. März 2017 um 08:28:

**Comment by mbalazs** [comment]
OK, it's done, I hope it's in the right place :)

**Comment by stefan-kolb** [comment]
LGTM 👍 
Thank you for your contribution :smile: !
And also thanks to @JohannesRudolph for the help and review!

**Comment by stefan-kolb** [comment]
One follow up question:
@podspace @mbalazs I don't see how one can deploy on their own private infrastructure and a non multi tenant private installation (virtual private) in the public cloud at your offering. Can you clarify the hosting options a bit? At the moment I would just say you offer a public hosting when taking a look at your documentation, pricing, etc.

**Comment by mbalazs** [comment]
We have marked the private and virtual private options because we are planning to offer dedicated, managed OpenShift deployments with the possibility of having the whole infrastructure on-premise. You are right that this offer is not present on the website yet.
We are planning to make it public in about a month. Is it OK to leave it as it is until then, or should we remove that option for now?

**Comment by stefan-kolb** [comment]
I'd be happy if we can update this when it is actually available to customers! I'll do that for you. You can just submit an update when it is ready! Thanks 😄

**Comment by mbalazs** [comment]
Great, we'll let you know then. :) Thank you!

**Pull request merged**
