### PR TITLE
Adding D2C

### PR DESCRIPTION
**Pull request by Santinell**
I have added D2C PaaS ( https://d2c.io )

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Thank you for your contribution :smile: !
Maybe you want to add a set of possible infrastructures (geographical regions) as this is not inferred automatically yet.

**Comment by Santinell** [comment]
D2C is not a public PaaS, user can choose any region of integrated providers ( DO and AWS now and Azure soon ) or add his own server into interface.

**Comment by stefan-kolb** [comment]
Ah ok, right, then you need to remove the `public true` attribute as this is covered by the `private true` attribute.

**Comment by stefan-kolb** [comment]
Will do that for you, thanks for the addition!

**Comment by stefan-kolb** [comment]
Actually you only deploy to public cloud providers in a private environment, right?! That is covered by virtual private cloud deployment attribute.

**Comment by Santinell** [comment]
We provide Logs, Metrics and deployment from our servers (and CI will be in the future). All other infrastructure is owned by user.
Hmm... so we should write private: false, public: false, vps: true?
VPS usually means Virtual Private Server... I really don't know...

**Comment by Santinell** [comment]
When I talked about user's infrastructure I meant that users can add servers to interface with their credentials of providers or by using special script on already existing server.

**Pull request merged**
