### PR TITLE
Added PythonAnywhere PaaS.

### PR DESCRIPTION
**Pull request by gpjt**
Hi there,

I work at PythonAnywhere; this is a first cut at adding a PaaS profile for our system.  Corrections gratefully accepted!  BTW, let me know what we need to do to make this vendor-verified; you can email me at giles@pythonanywhere.com.

Cheers,

Giles

### CODE REVIEW

**Comment by stefan-kolb** [comment]
Hi,

Thanks for your pull request :+1:.

Your profile is `vendor_verified` if the attribute is set, as it is the case already. So nothing more to do :smile: 

Few things to note here:

We also need two logos inside https://github.com/stefan-kolb/paas-profiles/tree/master/public/img/vendor in 400x400 and 80x80px sizes.

On profile consistency: 

It states your supporting Tomcat and Rails. However, you only have Python defined as a runtime. That won't work because of consistency reasons. It is also not clear how you may support them. Should be probably removed from the profile.

Also, for me it looks like as your database section is not correct: https://help.pythonanywhere.com/pages/KindsOfDatabases

Adding services to the add-ons section (see https://github.com/stefan-kolb/paas-profiles#add-on) must guarantee that they are accessible via SSO and paid via Pythonanywhere bill. Is this the case?

It is also not clear to me how a user can programmatically scale vertically and horizontally on your system (cannot find anything in the documentation).

Best,

Stefan

**Comment by gpjt** [comment]
Hi there,

I've added the images.  I'm a bit confused by some of your other comments though:

* Rails/Tomcat -- I don't see either of those anywhere in the JSON file.  Is there some default that I have to override?
* Databases should be MySQL and Postgres; we don't really want to promote SQLite, which isn't suitable for production sites (at least on our system).  Are you seeing any others?
* We don't have any add-ons in the JSON.  

Re: scaling -- it's not programmatic, but you can scale by upgrading your account via the web site (adding web workers, which automatically adds RAM).


Cheers,

Giles

**Comment by gpjt** [comment]
Wait, hang on.  For some crazy reason what I see in the PR isn't the same as what's in my repo.  I see where you're seeing the databases, add-ons and rails/tomcat stuff now.  Investigating...

**Comment by gpjt** [comment]
OK, something weird was happening with Sublime and my changes to the default template just weren't saving.  Sorry for the confusion!  A sane JSON file should be there now.

**Comment by gpjt** [comment]
OK, I've fixed a couple of silly errors in my JSON.  It looks like there's still a problem with the WSGI (standard Python web middleware) that I've put in into our profile; anything I can do about that?

**Comment by stefan-kolb** [comment]
I think you need to remove `Generic WSGI`from frameworks as it is already included as middleware.
You can also review messages of the CI server by clicking on the details link in the check box or https://travis-ci.org/stefan-kolb/paas-profiles/builds/82211192 for this build.

**Comment by gpjt** [comment]
I've removed the "Generic WSGI" bit, but there's still a CI error:

    1) Failure:
    Profiles::TestConsistency#test_software_intersection [/home/travis/build/stefan-kolb/paas-profiles/test/profiles/test_consistency.rb:38]:
    Intersecting software wsgi. No software entity may be included in another category.

**Comment by stefan-kolb** [comment]
I got the problem. Will merge the PR now.
Please make sure to update the profile from time to time!

Thanks again! :+1:

**Comment by gpjt** [comment]
Awesome, thanks!  What was the problem?  (Just so that I don't accidentally re-introduce it when I update the profile :-)

**Comment by stefan-kolb** [comment]
`Intersecting software wsgi. No software entity may be included in another category.` indicates that `wsgi` can only be used in one category (and this means globally among all profiles for consistency).
`wsgi` was specified as `framework` in other profiles before, so it coulddn't be used as middleware in this profile.

**Comment by gpjt** [comment]
Ah, right.  What was the fix?  Is there anything I need to avoid doing when I update it in the future?

**Comment by stefan-kolb** [comment]
See this commit https://github.com/stefan-kolb/paas-profiles/commit/e9d0be021554450ad1557a73b11f8148293644b2 for clarification.

**Comment by gpjt** [comment]
Got it, thanks!

**Pull request merged**
