### PR TITLE
Update AppFog DC Locations

### PR DESCRIPTION
**Pull request by JohannesRudolph**
see commits

### CODE REVIEW

**Comment by stefan-kolb** [comment]
I'd like to keep the region names here instead of the abstract data center names. See https://www.ctl.io/data-centers/. Is more meaningful than US West and East, what do you think?

**Comment by JohannesRudolph** [comment]
No preference either way, US West and US East is what the App Fog control panel (their UI) lists them at. Not sure which physical DC locations host them though, couldn't trace it as ipinfo.io lists both locations as Chesterfield, Missouri: 

https://api.uswest.appfog.ctl.io
https://api.useast.appfog.ctl.io

**Comment by stefan-kolb** [comment]
Maybe the API is hosted on just one Node? Just the applications are run in other geographical regions.

**Comment by stefan-kolb** [comment]
Ok, let's just use these names for now until we know more.

**Pull request merged**
