### PR TITLE
Fix CF Provider runtime etc. support warnings

### PR DESCRIPTION
**Pull request by JohannesRudolph**
copy runtimes, middleware and framework sections from cloud foundry to all cf providers. need to find a way to automate this but at least it fixes all warnings for now

### CODE REVIEW

**Comment by stefan-kolb** [comment]
I'm not sure if this is really wanted, because some providers just don't support the most recent runtimes etc. The warning were initially created to show potential differences that might even exist in reality. I'll take a closer look tomorrow or on Monday.

**Comment by JohannesRudolph** [comment]
In any case, Cloud Foundry supports Heroku Buildpacks. If a buildpack is
not pre-installed at the provider, that's not a problem as a manifest.yml
can just instruct CF to grab it off github

As far as my testing goes, most support the diego runtime as well (will
double check!. )This makes it possible to deploy docker containers (so they
literally support running almost anything).

**Comment by stefan-kolb** [comment]
Yeah, that's not the case here as we mark this with `extensible`. It's more about official support and default settings. Of course this is getting less important than it was a few years ago when we didn't have that stable platforms and buildpack support.

**Comment by RochesterinNYC** [comment]
I don't know that you can really say that CF supports Heroku buildpacks. CF supports the ability to try and run any heroku buildpack on CF but there isn't a guarantee that specific buildpack will work. 

The point about Docker container support is true though. And it's easy enough in CF to create and use buildpacks that bring in any dependencies as an alternative.

**Pull request closed without merging**
