### PR TITLE
Appenda 6.0

### PR DESCRIPTION
**Pull request by dutronlabs**
We've updated this information for the most current version of our product, Apprenda v5.5.5. We will set up regular touchpoints during releases to make sure all information is relevant.

Thanks!
-Chris

### CODE REVIEW

**Comment by stefan-kolb** [comment]
@dutronlabs First of all, thanks for your PR :+1: 

Before I can merge your request, we need to fix and discuss a few things. 
Sorry for being a little nitpicky, but we need to keep the profiles as consistent as possible between vendors. 
All information on specific attributes can also be found in the [Readme](https://github.com/stefan-kolb/paas-profiles/blob/master/README.md).

1. You should update `'revision': '2015-04-15'` to reflect the last change of the profile.
2. Since you are providing authorative information, you may also add `'vendor_verified': '2015-04-15'`
3. `status_since` refers to the last `status` change, in this case when your offering went `production`. You can change this to the date when `v5.5` went into production, however, this will make your offering look "new" in terms of maturity, which is not necessarily what you want.
4. Type can only be `Generic, SaaS-centric, IaaS-centric`. In your case this is `SaaS-centric`in my opinion. See also this [paper](http://www.uni-bamberg.de/?id=85921). If a PaaS is available as private PaaS, this is depicted by the `hosting` attribute.
5. You don't have a matching `pricing` model?
6. JBoss and Tomcat are `middleware` products not `frameworks` from my point of view.
7. Do your `addons` include hosting locations for Apprenda? This should be in `infrastructures` then.
8. In which way is Apprenda `extensible`? Can i really add new runtime languages or native services to it, like with Buildpacks?

**Comment by dutronlabs** [comment]
Thanks so much for the feedback, we'll get this sorted today and resubmit.



—

**Comment by dutronlabs** [comment]
Hi, 

This is ready to go for Apprenda 6.0. Let me know if you have any questions (or if I missed anything after review)

**Comment by stefan-kolb** [comment]
Hi,

I opened a new branch to be able to make the necessary changes myself.
You can take a look at the changes here and discuss them if you want before I'll merge it.
See #133.

Cheers, Stefan

**Comment by stefan-kolb** [comment]
Closing in favor of #133.

**Pull request closed without merging**
